### PR TITLE
Update tests to use ACA-Py 0.9.0

### PR DESCRIPTION
**Pull request by dbluhm**

### CODE REVIEW

**Comment by dbluhm** [comment]
Code quality check needs to be bumped from 3.6 to 3.9 (can also bump the runner to ubuntu-latest at the same time). Re: timeouts, we would need to adjust the timeouts on the `record_with_value` calls which is actually happening in the `protocols` we're call, I think. We'd need to update the acapy-minimal-example controller to allow us to set a default timeout. Might be best to save that for another day. (Feel like opening a ticket on the AME repo for that? :slightly_smiling_face:)

**Comment by anwalker293** [comment]
Sure! You've got it! (I'm assuming undo the timeouts I changed then, right? (whoops))

**Comment by anwalker293** [comment]
🎉

**Comment by dbluhm** [comment]
Superseded by #41; thanks!

**Pull request closed without merging**
